CREATE TABLE IF NOT EXISTS matafuegos (
    id_matafuego INT AUTO_INCREMENT PRIMARY KEY,
    numero VARCHAR(50) NOT NULL,
    sector VARCHAR(200) NOT NULL,
    clase VARCHAR(20) NOT NULL,
    recarga DATE DEFAULT NULL,
    vencimiento DATE NOT NULL,
    id_camion INT DEFAULT NULL,
    observaciones TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
